name: Security Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  security:
    runs-on: ubuntu-latest

    permissions:
      security-events: write

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
    # checkout
    - name: Checkout
      uses: actions/checkout@v4

    # CodeQL
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v4
      with:
        languages: javascript

    - name: Autobuild
      uses: github/codeql-action/autobuild@v4

    - name: Run CodeQL
      uses: github/codeql-action/analyze@v4

    # Secret scan
    - name: Secret Scan
      run: |
        echo "Running secret scan..."
        
        if grep -r "PASSWORD" .; then
          echo "Hardcoded password found"
          exit 1
        fi

        if grep -r "API_KEY" .; then
          echo "API key exposed"
          exit 1
        fi

    # DAST
    - name: OWASP ZAP Scan
      uses: zaproxy/action-baseline@v0.11.0
      with:
        target: ${{ secrets.APP_URL }}